<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.P6Lg9RW' shared service.

return $this->privates['.service_locator.P6Lg9RW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'partenaire' => ['privates', '.errored..service_locator.P6Lg9RW.App\\Entity\\partenaire', NULL, 'Cannot autowire service ".service_locator.P6Lg9RW": it references class "App\\Entity\\partenaire" but no such service exists.'],
    'partenaireRepository' => ['privates', 'App\\Repository\\PartenaireRepository', 'getPartenaireRepositoryService.php', true],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
], [
    'partenaire' => 'App\\Entity\\partenaire',
    'partenaireRepository' => 'App\\Repository\\PartenaireRepository',
    'serializer' => '?',
]);
