<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.L1BB.Os' shared service.

return $this->privates['.service_locator.L1BB.Os'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ApiController::ajoutp' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ApiController::bloquer' => ['privates', '.service_locator.U2OyWts', 'get_ServiceLocator_U2OyWtsService.php', true],
    'App\\Controller\\ApiController::depot' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\ApiController::register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\ApiController::show' => ['privates', '.service_locator.iW_buO_', 'get_ServiceLocator_IWBuOService.php', true],
    'App\\Controller\\ApiController::update' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
    'App\\Controller\\PartenaireController::delete' => ['privates', '.service_locator.xrohzKf', 'get_ServiceLocator_XrohzKfService.php', true],
    'App\\Controller\\PartenaireController::edit' => ['privates', '.service_locator.xrohzKf', 'get_ServiceLocator_XrohzKfService.php', true],
    'App\\Controller\\PartenaireController::index' => ['privates', '.service_locator.0VWx6lC', 'get_ServiceLocator_0VWx6lCService.php', true],
    'App\\Controller\\PartenaireController::show' => ['privates', '.service_locator.xrohzKf', 'get_ServiceLocator_XrohzKfService.php', true],
    'App\\Controller\\SuperadminController::superadmin' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\ApiController:ajoutp' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ApiController:bloquer' => ['privates', '.service_locator.U2OyWts', 'get_ServiceLocator_U2OyWtsService.php', true],
    'App\\Controller\\ApiController:depot' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\ApiController:register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\ApiController:show' => ['privates', '.service_locator.iW_buO_', 'get_ServiceLocator_IWBuOService.php', true],
    'App\\Controller\\ApiController:update' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
    'App\\Controller\\PartenaireController:delete' => ['privates', '.service_locator.xrohzKf', 'get_ServiceLocator_XrohzKfService.php', true],
    'App\\Controller\\PartenaireController:edit' => ['privates', '.service_locator.xrohzKf', 'get_ServiceLocator_XrohzKfService.php', true],
    'App\\Controller\\PartenaireController:index' => ['privates', '.service_locator.0VWx6lC', 'get_ServiceLocator_0VWx6lCService.php', true],
    'App\\Controller\\PartenaireController:show' => ['privates', '.service_locator.xrohzKf', 'get_ServiceLocator_XrohzKfService.php', true],
    'App\\Controller\\SuperadminController:superadmin' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
], [
    'App\\Controller\\ApiController::ajoutp' => '?',
    'App\\Controller\\ApiController::bloquer' => '?',
    'App\\Controller\\ApiController::depot' => '?',
    'App\\Controller\\ApiController::register' => '?',
    'App\\Controller\\ApiController::show' => '?',
    'App\\Controller\\ApiController::update' => '?',
    'App\\Controller\\PartenaireController::delete' => '?',
    'App\\Controller\\PartenaireController::edit' => '?',
    'App\\Controller\\PartenaireController::index' => '?',
    'App\\Controller\\PartenaireController::show' => '?',
    'App\\Controller\\SuperadminController::superadmin' => '?',
    'App\\Controller\\ApiController:ajoutp' => '?',
    'App\\Controller\\ApiController:bloquer' => '?',
    'App\\Controller\\ApiController:depot' => '?',
    'App\\Controller\\ApiController:register' => '?',
    'App\\Controller\\ApiController:show' => '?',
    'App\\Controller\\ApiController:update' => '?',
    'App\\Controller\\PartenaireController:delete' => '?',
    'App\\Controller\\PartenaireController:edit' => '?',
    'App\\Controller\\PartenaireController:index' => '?',
    'App\\Controller\\PartenaireController:show' => '?',
    'App\\Controller\\SuperadminController:superadmin' => '?',
]);
