<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1YFnqsC\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1YFnqsC/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container1YFnqsC.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container1YFnqsC\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \Container1YFnqsC\srcApp_KernelTestDebugContainer([
    'container.build_hash' => '1YFnqsC',
    'container.build_id' => '9ddece6a',
    'container.build_time' => 1564477736,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1YFnqsC');
