<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX7E2a9V\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX7E2a9V/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX7E2a9V.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX7E2a9V\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerX7E2a9V\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'X7E2a9V',
    'container.build_id' => 'af4332ae',
    'container.build_time' => 1564514072,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX7E2a9V');
