<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXKZZxHL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXKZZxHL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXKZZxHL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXKZZxHL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXKZZxHL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XKZZxHL',
    'container.build_id' => '45ec1486',
    'container.build_time' => 1564119584,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXKZZxHL');
