<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWixRizJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWixRizJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWixRizJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWixRizJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWixRizJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WixRizJ',
    'container.build_id' => 'f622a5cf',
    'container.build_time' => 1564243171,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWixRizJ');
